title: Jonathan Zamora
baseurl: "/personal_site"
markdown: kramdown

# Build settings
remote_theme: ankitsultana/researcher@gem 
ins_logo: "./code.gif"

footer: yes
footer_url: "https://github.com/jonzamora18"
footer_text: "Page design by Jonathan Zamora"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/personal_site/"
 - name: "Resume"
   link: "jonathan_zamora_cs_resume.pdf"
 - name: "Contact"
   link: "contact"