title: Jonathan Zamora
url: "https://jonzamora.dev"
baseurl: ""
favicon: "favicon.ico"

# Build settings
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
# ins_logo:

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This guy makes a nice website"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Resume"
   link: "Jonathan-Zamora-Resume.pdf"