title: Jonathan Zamora
url: "https://jonzamora.dev"
baseurl: ""
favicon: "favicon.ico"

# Build settings
remote_theme: ankitsultana/researcher@gem 
markdown: kramdown
ins_logo: "./code.gif"

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "This guy makes a nice website"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/"
 - name: "Resume"
   link: "jonathan_zamora_cs_resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Lists"
   link: "lists"